version: "3.6"
services: 
    flask:
        build: ./
        depends_on: 
            postgres:
                condition: service_healthy
        env_file:
            - .env
        ports: 
            - "${FLASK_HOST_PORT}:5000"
        restart: always
    postgres:
        image: "postgres:alpine"
        env_file:
            - .env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U test -d test"]
            interval: 5s
            timeout: 2s
            retries: 3
        restart: always
