version: "3.6"
services: 
    flask:
        build: ./
        depends_on: 
            postgres:
                condition: service_healthy
        ports: 
            - "5000:5000"
        environment:
            STAGE: "postgres"
            SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://test:test@postgres:5432/cached_db"
        restart: always
    postgres:
        image: "postgres:alpine"
        environment:
            POSTGRES_USER: "test"
            POSTGRES_PASSWORD: "test"
            POSTGRES_DB: "cached_db"
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U test -d cached_db"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: always