version: "3.6"
services: 
    flask:
        build: ./
        env_file:
            - .env
        ports: 
            - "${FLASK_HOST_PORT}:5000"
        volumes:
            - db-data:/app/sta_dashboard/data
        restart: always
volumes:
    db-data: