version: "3.6"
services: 
    flask:
        build: ./
        depends_on: 
            postgres:
                condition: service_healthy
        environment:
            - .env
        ports: 
            - "5000:5000"
        restart: always
    postgres:
        image: "postgres:alpine"
        environment:
            - .env
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U test -d cached_db"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: always